# Generated by Django 2.0.7 on 2019-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('furniture', models.CharField(max_length=100)),
                ('drawer_section', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(default='', max_length=200)),
                ('item_count', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
